// <auto-generated />
namespace TestCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deleteing_id_columns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteing_id_columns));
        
        string IMigrationMetadata.Id
        {
            get { return "202012041430292_deleteing_id_columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
