// <auto-generated />
namespace TestCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ЗаменаТиповКлючей_ПеречисленияНаИнт : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ЗаменаТиповКлючей_ПеречисленияНаИнт));
        
        string IMigrationMetadata.Id
        {
            get { return "202101160753271_ЗаменаТиповКлючей_ПеречисленияНаИнт"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
