// <auto-generated />
namespace TestCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class simpleUpdate15_52 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(simpleUpdate15_52));
        
        string IMigrationMetadata.Id
        {
            get { return "202101201052526_simpleUpdate15_52"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
