// <auto-generated />
namespace TestCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddModePowerTODevice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddModePowerTODevice));
        
        string IMigrationMetadata.Id
        {
            get { return "202101211045157_AddModePowerTODevice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
