// <auto-generated />
namespace TestCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _19_01выбранноесостояниебезсвязиспланом : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_19_01выбранноесостояниебезсвязиспланом));
        
        string IMigrationMetadata.Id
        {
            get { return "202101111402158_19_01 выбранное состояние без связи с планом"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
