// <auto-generated />
namespace TestCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_partian_inВыбранноеСостояние : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_partian_inВыбранноеСостояние));
        
        string IMigrationMetadata.Id
        {
            get { return "202101101704583_Add_partian_inВыбранноеСостояние"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
