// <auto-generated />
namespace TestCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _18_46 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_18_46));
        
        string IMigrationMetadata.Id
        {
            get { return "202101111346445_18_46"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
