// <auto-generated />
namespace TestCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SimpleUpdate19_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SimpleUpdate19_01));
        
        string IMigrationMetadata.Id
        {
            get { return "202101190926036_SimpleUpdate19_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
